# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# https://goreleaser.com/customization/build/
project_name: scf-proxy
gomod:
  proxy: true
builds:
  - main: ./cmd/main.go
    id: "scf-proxy"
    env: [CGO_ENABLED=0]
    binary: main
    ldflags:
      - -s -w -X main.Versionm={{.Version}} -X main.Commitm={{.ShortCommit}} -X main.Datem={{.Date}} -X main.Branchm={{.Branch}}
    goos:
      - linux
    goarch:
      - amd64

  - main: ./cmd/client.go
    id: "scf-client"
    env: [CGO_ENABLED=0]
    binary: scf-client
    ldflags:
        - -s -w -X main.Version={{.Version}} -X main.Commit={{.ShortCommit}} -X main.Date={{.Date}} -X main.Branch={{.Branch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    allow_different_binary_count: true
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'